// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAss2VkmJ-RJjWR9zKe63iqraKnaAKrnYk',
    appId: '1:245196026042:web:cece596c00db6327b69283',
    messagingSenderId: '245196026042',
    projectId: 'green-tech-f15a5',
    authDomain: 'green-tech-f15a5.firebaseapp.com',
    storageBucket: 'green-tech-f15a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUfYERP3Qcw0qbJGpZaWQ9wIBjsR-RaSo',
    appId: '1:245196026042:android:660edb391002fd12b69283',
    messagingSenderId: '245196026042',
    projectId: 'green-tech-f15a5',
    storageBucket: 'green-tech-f15a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHhMZlZTcn9giMIJ9Fc3LDxtpDbHwZs3U',
    appId: '1:245196026042:ios:7dbbeb44aaa76b1cb69283',
    messagingSenderId: '245196026042',
    projectId: 'green-tech-f15a5',
    storageBucket: 'green-tech-f15a5.appspot.com',
    iosBundleId: 'com.example.greenProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHhMZlZTcn9giMIJ9Fc3LDxtpDbHwZs3U',
    appId: '1:245196026042:ios:438f0670f7eb466bb69283',
    messagingSenderId: '245196026042',
    projectId: 'green-tech-f15a5',
    storageBucket: 'green-tech-f15a5.appspot.com',
    iosBundleId: 'com.example.greenProject.RunnerTests',
  );
}
